name: 'Simple PR Create'
description: 'Simple Pull Request creation to Github based on octokit'
inputs:
  authentication:
    description: 'Authentication Token of Github if any'
    required: false
  head:
    description: 'Head branch where the Pull Request originate from'
    required: true
  base:
    description: 'Base branch where the Pull Request will merge to'
    required: true
    default: 'master'
  title:
    description: 'Pull Request Title'
    required: true
    default: 'Pull Request by Github Action Bot'
  body:
    description: 'Pull Request Body'
    required: true
    default: 'This Pull Request is created by Github Action Bot'

runs:
  using: 'node12'
  main: './build/index.js'